

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-platform
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Inckrisz/argocd-js.git
    targetRevision: HEAD
    path: platforms/istio-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
