apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-a
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://inckrisz.github.io/argocd-js
    targetRevision: helming2
    chart: app1
    path: docs
    helm:
     valueFiles:
      - values.yaml
  destination:
   server: https://kubernetes.default.svc
   namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
