apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: ghcr.io/inckrisz/app1-js:latest
          ports:
            - containerPort: 4000
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do curl http://app-a:3000/data; sleep 10; done"]
          imagePullPolicy: IfNotPresent
