apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app2
  namespace: argo
spec: 
  destination: 
    namespace: app2
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: app2
    repoURL: "https://github.com/Inckrisz/argocd-js"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
