apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-a
  namespace: default
spec:
  host:  app-a.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
