apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-a-vs
  namespace: default
spec:
  hosts:
    - app1.demo.hu
  gateways:
    - js-app-gateway
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /data
      route:
        - destination:
            host: app-a.default.svc.cluster.local
            port:
              number: 80
