apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: ghcr.io/inckrisz/app1-js:latest
          ports:
            - containerPort: 3000
        - name: traffic-simulator
          image: curlimages/curl
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                curl --retry 3 --retry-delay 2 --connect-timeout 5 http://app-b.default.svc.cluster.local:4000/data;
                sleep 30;
              done
