apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.name }}-vs
  namespace: default
spec:
  hosts:
    - {{ .Values.virtualHost }}
  gateways:
    - mesh
    - js-app-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.name }}.default.svc.cluster.local
            port:
              number: 80
